version: 2.1
orbs:
  cli: circleci/circleci-cli@0.1.7
  orb-tools: circleci/orb-tools@10.0.0
executors:
  cli:
    docker:
      - image: 'circleci/circleci-cli:latest'
    working_directory: /tmp/orbs


master_only: &master_only
  filters:
    branches:
      only: master

orb1_pre_steps: &orb1_pre_steps
  pre-steps: 
    - checkout
    - files-changed:
        path: "orb1/orb1.yml"

orb2_pre_steps: &orb2_pre_steps
  pre-steps: 
    - checkout
    - files-changed:
        path: "orb2/orb2.yml"

commands:
  files-changed:
    parameters:
      path:
        type: string
    steps:
      - run:
          command: |
            changes() {
              git diff --name-only --diff-filter=AMDR @~..@
            }
            cd /home/circleci/project
            changes | grep << parameters.path >>
            exit_code=$?
            if [ $exit_code -ne 0 ]; then
              echo "The path << parameters.path >> was not modified. Will skip build of orb."
              circleci step halt
            else
              exit $exit_code
            fi

jobs:
  publish-orb:
    parameters:
      working_directory:
        type: string
      orb-name:
        type: string  
    working_directory: << parameters.working_directory >>
    executor: cli
    steps:
      - orb-tools/dev-promote-from-commit-subject:
          orb-name:  << parameters.orb-name >>
          add-pr-comment: false
          fail-if-semver-not-indicated: true
workflows:
  build:
    jobs:
      - orb-tools/publish-dev:
          <<: *orb1_pre_steps
          name: "publish-dev-orb-1"
          workspace-root: "/home/circleci/project"
          orb-path: "orb1/orb1.yml"          
          validate: true
          orb-name: "bmbferreira/orb1"
          checkout: true
      - orb-tools/publish-dev:
          <<: *orb2_pre_steps
          name: "publish-dev-orb-2"
          workspace-root: "/home/circleci/project"
          orb-path: "orb2/orb2.yml"          
          validate: true
          orb-name: "bmbferreira/orb2"
          checkout: true
      - apply-approval:
          type: approval
          requires:
            - publish-dev-orb-1
            - publish-dev-orb-2
          <<: *master_only
      - publish-orb:
          <<: *orb1_pre_steps
          name: "publish-orb-1"
          working_directory: "/tmp/orbs/orb1"          
          orb-name: "bmbferreira/orb1"
          <<: *master_only
          requires:
            - apply-approval
      - publish-orb:
          <<: *orb2_pre_steps
          name: "publish-orb-2"
          working_directory: "/tmp/orbs/orb2"          
          orb-name: "bmbferreira/orb2"
          <<: *master_only
          requires:
            - apply-approval
          
          
          
